### ISSUE TITLE
Exception on application exit if MIDI device was disconnected

### ISSUE THREAD

**Issue by calinburloiu** [calinburloiu/microtonalist#21]
If a Roland FP-90 digital piano is turned off and the application is exited the following exception occurs:

```
Exception in thread "Thread-1" java.lang.IllegalStateException: Can't call send() with a closed receiver
	at uk.co.xfactorylibrarians.coremidi4j.CoreMidiReceiver.send(CoreMidiReceiver.java:57)
	at org.calinburloiu.music.microtuner.MidiTuner.tune(Tuner.scala:47)
	at org.calinburloiu.music.microtuner.MicrotonalistApp$$anon$1.org$calinburloiu$music$microtuner$LoggerTuner$$super$tune(MicrotonalistApp.scala:90)
	at org.calinburloiu.music.microtuner.LoggerTuner.tune(Tuner.scala:36)
	at org.calinburloiu.music.microtuner.LoggerTuner.tune$(Tuner.scala:33)
	at org.calinburloiu.music.microtuner.MicrotonalistApp$$anon$1.tune(MicrotonalistApp.scala:90)
	at org.calinburloiu.music.microtuner.MicrotonalistApp$$anon$2.run(MicrotonalistApp.scala:111)
```

**Comment by calinburloiu** [comment]
Similar issue when switching tuning after disconnecting the device:

```
Exception in thread "AWT-EventQueue-0" org.calinburloiu.music.microtuner.MidiTunerException: Failed to send tune message to device! Did you disconnect the device?
	at org.calinburloiu.music.microtuner.MidiTuner.tune(Tuner.scala:51)
	at org.calinburloiu.music.microtuner.MicrotonalistApp$$anon$1.org$calinburloiu$music$microtuner$LoggerTuner$$super$tune(MicrotonalistApp.scala:90)
	at org.calinburloiu.music.microtuner.LoggerTuner.tune(Tuner.scala:36)
	at org.calinburloiu.music.microtuner.LoggerTuner.tune$(Tuner.scala:33)
	at org.calinburloiu.music.microtuner.MicrotonalistApp$$anon$1.tune(MicrotonalistApp.scala:90)
	at org.calinburloiu.music.microtuner.TuningSwitch.apply(TuningSwitch.scala:39)
	at org.calinburloiu.music.microtuner.TuningListFrame.$anonfun$new$1(TuningListFrame.scala:46)
	at javax.swing.JList.fireSelectionValueChanged(JList.java:1802)
	at javax.swing.JList$ListSelectionHandler.valueChanged(JList.java:1816)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:164)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:211)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:405)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:415)
	at javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:459)
	at javax.swing.JList.setSelectedIndex(JList.java:2216)
	at javax.swing.plaf.basic.BasicListUI$Actions.changeSelection(BasicListUI.java:2182)
	at javax.swing.plaf.basic.BasicListUI$Actions.actionPerformed(BasicListUI.java:1866)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1668)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2929)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at java.awt.Component.processEvent(Component.java:6316)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:835)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1103)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:974)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:800)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalStateException: Can't call send() with a closed receiver
	at uk.co.xfactorylibrarians.coremidi4j.CoreMidiReceiver.send(CoreMidiReceiver.java:57)
	at org.calinburloiu.music.microtuner.MidiTuner.tune(Tuner.scala:49)
	... 53 more
```
